language: node_js

node_js:
  - '10'
  - '12'
  - '14'

env:
  - PACKAGE=idyll-ast
  - PACKAGE=idyll-compiler
  - PACKAGE=idyll-components
  - PACKAGE=idyll-cli
  - PACKAGE=idyll-document
  - PACKAGE=idyll-layouts
  - PACKAGE=idyll-themes

cache: yarn

script: cd packages/$PACKAGE && npm test
